### ISSUE TITLE
Port 3000 clashes with local SSO instances

### ISSUE THREAD

**Issue by chasingSublimity** [cgrayson/h#2]
After launching a Rich UI with the `--server` flag, I'll often end up redirected to the SSO login page. (Even when I'm running neither nginx or SSO locally). I then have to hunt down the docker/sso/nginx/whatever processes that are occupying port 3000. 

While not a huge deal, it's kind of a pain. Would it be worth switching the port number to 3030? Or adding a flag option allowing the user to set their own port? Happy to submit a PR in either case.

EDIT: oh wait, looking at the code, i think i see a `-p` option for setting a port. My b. In that case, I'm happy to add a few lines to the readme about the `-p` flag. :D

**Comment by cgrayson** [comment]
Good points, and my bad for not including `-p`/`--port` in the Readme before. It's there now, and the default is now `3033`. (And the UI modal iframe is the right height now, too.)
